mozilla/notes

- src/sidebar/options/options.html
- src/sidebar/panel.html
- src/sidebar/panel.js
Ref: #18
Still have 2 warnings regarding `<style>` tag and `style=""` attribute:
```sh
✗ $(npm bin)/htmllint 'src/**/*.html'
src/sidebar/panel.html: line 8, col 3, the style tag is banned
src/sidebar/options/options.html: line 9, col 4, the `style` attribute is banned
[htmllint] found 2 errors out of 2 files
```
---
**UPDATE:** This PR is mostly just whitespace tweaking, so the more easily digestible diff is https://github.com/mozilla/notes/pull/19/files?w=1
> Fixing up results from htmllint

- src/sidebar/styles.css
Ref: [/src/sidebar/panel.html:34](https://github.com/mozilla/notes/blob/5dd39837054c28d75bdd94e46fc1f4e5790fbd87/src/sidebar/panel.html#L34):
```html
<button id="enable-sync">Enable Sync</button>
```
> Fix bad button id in CSS

- locales/en-US/notes.properties
- package.json
- scripts/build-locales.js
For https://github.com/mozilla/notes/issues/42
> WIP : Add localization support

- .gitignore
- docs/localization.md
- locales/en-US/notes.properties
- package.json
- scripts/build-locales.js
- scripts/postinstall.sh
- src/manifest.json
- src/sidebar/panel.html
- src/sidebar/panel.js
For https://github.com/mozilla/notes/issues/42
TODO: get ltr/rtl working properly
Question:
- Should the name of the add-on be translated? i.e `notes`?
> feat(translations): call browser i18n for all strings

- docs/metrics.md
Note: the link to the Test Pilot standards will 404 while in review; for now, it can be read at https://github.com/mozilla/testpilot/blob/2538-ga-docs/docs/experiments/ga.md.
CC @johngruen, @clouserw
> Adds draft of metrics documentation.

- package.json
Take it or leave it, but I just realized I've been building the add-on locally with a bunch of bloated old vendor files which we aren't using anymore (which was doubling my extension size).
This should clean and rebuild the ./src/sidebar/vendor/* directory.
> Clean src/sidebar/vendor/ directory

- src/sidebar/panel.html
- src/sidebar/panel.js
- src/sidebar/styles.css
This a solution for issue #115. Currently, the only way to close the notification is by clicking the "Sync Your Notes" button again.
With this PR, the `close.svg` file has been added to the top-right corner of the notification. When clicked, the notification then disappears. This allows for a more user-friendly experience.
> "Close" button for the "Sync Your Notes" notification, fixes #115

- src/sidebar/panel.js
This commit is a quick fix to issue #72 - missing tooltips. Currently, Quill
has no support for native tooltips, rather relying on Bootstrap (which requires
jQuery). For usability purposes, I've added titles to the toolbar buttons
which appear when hovering over the buttons, similar to a tooltip but not as
styled. The titles themselves include the button's functionality ('Font size',
'Bold', 'Bulleted list', etc.) as well as the key-binding associated with it.
Currently, only the 'Bold' and 'Italic' formats included a default key-binding.
Following the documentation for adding additional bindings to the keyboard
module (found here: https://quilljs.com/docs/modules/keyboard/), I went ahead
and added three bindings for the buttons/formats in the toolbar without them
('strike', 'list: …
> Add key-bindings for toolbar buttons

- src/sidebar/panel.js
After the merge of #121, I realized I forgot to add spaces between the format
titles and their key bindings. Currently the titles look like so: `Bold(Ctrl+B)`.
With this PR, there is now a space between the two: `Bold (Ctrl+B)`.
> Tooltip styling fix

- src/sidebar/styles.css
Just downloaded Firefox Dev edition and started testing Notes on there. When
opening up the Sync note, I saw that there was a great deal of margin to it's
right (the note was not the full width of the sidebar like the Sync button).
On the regular edition of Firefox, the Sync note **was** the full width of the
sidebar. These small changes make it so that the Sync note is the full width of
the sidebar on both browsers.
**FF Dev edition - before:**
**FF regular edition - before:**
**FF Dev edition - after:**
**FF regular edition - after:**
> Fixed margin issue with Sync note on different browsers

- src/sidebar/panel.js
- src/sidebar/styles.css
Fixes #132 
Apparently it doesn't work properly. I filed https://github.com/quilljs/quill/issues/1582 about it.
> Use a no-drop pointer when dragging into the ql-editor.

- docs/metrics.md
- src/background.js
- src/sidebar/panel.js
This uses Port to handle open and close events. It works really gracefully.
However with this implementation open and close events doesn't have metrics about the content of the pad anymore because we don't have that information anymore when the pad is close. 
@chuckharmston can you tell us if it is acceptable?
> Handle open and close events.

- l10n.toml
This allows to run compare-locales in the Notes repo, check for errors in locales
```
compare-locales l10n.toml . `ls locales/`
```
> Add l10n.toml

- src/sidebar/styles.css
Adds the ellipsis ('...') to the end of the Sync button text when the sidebar is resized.
Tested on regular FF and FF Dev edition, as well as normal and RTL mode.
> Truncated Sync button, fixes #153

- locales/en-US/notes.properties
- package.json
- scripts/postinstall.js
- src/manifest.json
- src/sidebar/dark-svg/three-dots-dark.svg
- src/sidebar/panel.html
- src/sidebar/panel.js
- src/sidebar/styles-dark.css
- src/sidebar/styles.css
This adds the context menu for #208. Currently, the menu looks like so:
Work that still needs to be completed: 
~- [ ] 'Disable Sync'~
> Context Menu for Footer

- src/sidebar/panel.js
This initial commit fixes issues #253, #271, and #273. How these issues are fixed
is described below:
- #253: When a space (or any character) is entered at index 0 of the editor
with a link immediately following that character (as shown in the screen-grab
for the issue), any formatting that is applied to the link will be applied
to that character. The issue here was that the `link` format was being applied
to space characters, but this is fixed by removing the `link` format from the
first character of the editor.
- #271 & #273: These issues involve the links getting any format they had
applied to them removed as soon as the link-editing format was escaped. The
fix for this was to capture and save the format of the link (formats like
bold, italics, font size, etc.) then applying those same …
> Support for Links

- src/sidebar/panel.js
This brings in several bug fixes for the `Links` format. Specific issues fixed in this first commit are:
- #179 - links underlined and clickable (even with other formatting options - was an issue with last PR)
- #271 - formatted link not keeping other formatting options (like `bold`, `italics`, etc.)
- #273 - <kbd>Space</kbd> and <kbd>Tab</kbd> characters before link are formatted as `links`
- #286 - first letter of link not formatted as `link` when pasted into bulleted or ordered list
> Fix for Links Issues

- package.json
- src/background.js
- src/manifest.json
To avoid Firefox's autoupdate to the Test Pilot version. Fixes confusions like in #332.
> Bump version to 1.9.0dev

- src/sidebar/styles-dark.css
- src/sidebar/styles.css
**Changes made result in the following:**
- fixed the heading dropdown border overlap issue
- replicated `:hover` and `:active` styles from the light theme
- added a border to tooltips to make them stand out better
**And a gif of the changes made (sorry for the poor quality):**
> Dark Theme touchups

- CODEOWNERS
This should trigger a request review for any changes to the .properties file
In the past hours 10 strings landed without any review, and that's not optimal.
> Add CODEOWNERS for l10n reviews

- locales/en-US/notes.properties
> Update Sync strings and add better L10N descriptions

- src/sidebar/styles.css
fixes: #527 
The changes made can be previewed below
I have highlighted the background of the menu icon to make the change prominent , as shown below
> menu icon is now vertically centered

- src/sidebar/panel.js
fixes: #519 
I have fixed this but the only problem is that the size of the button background has been increased, **which can only be seen when we hover over the menu button**. Well according to me all things work fine, however if you don't prefer these changes then I will have to approach this some other way.
Here is a GIF of the changes
> The Firefox Notes feedback page is no longer wrongly opened on clicking the area around the 'notes' menu button

- src/sidebar/panel.js
fixes : #597 
Changes can be seen in the GIF below
> syncing used instead of saving while logged in

- docs/metrics.md
- src/background.js
- src/sidebar/editor.js
> Upgrading metrics.

- src/background.js
- src/sidebar/panel.js
fixes: #599 
GIF of changes is as follows
___________
@Natim , sorry for the delay
> The previously used Sync email is wrongly displayed as a tooltip after logging out

- src/sidebar/editor.js
- src/sidebar/panel.js
- src/sidebar/styles-dark.css
- src/sidebar/styles.css
Responding to issue #574 , added styling to make the "Synced at (time)" text black. First pull request, let me know how this looks!
> last sync text color fixed (#574)

- src/sidebar/panel.js
fixes: #638 
This bug has occurred because of me. So I have fixed it
Please see the below GIF
> After logging off from "Firefox Notes", the "Give Feedback" button is now displayed in the other opened windows

- src/sidebar/panel.js
> Fix that thing when there are extra spaces in initial content

- locales/en-US/notes.properties
- src/fxa-utils.js
- src/manifest.json
- src/sidebar/app/components/Footer.js
- src/sidebar/static/scss/footer.scss
Revamp of #674 
We will go with the **Export as HTML** only for now and wait for a discussion about the Markdown feature altogether before implementing its export.
> Export as HTML

- src/sidebar/app/components/Footer.js
> Add a title attribute to the export as HTML menu item.

- src/background.js
This disables the context menu item 'Send to Notes' from being created / rendered in Notes itself. The `<all_urls>` document url patter does not match `resource://...` paths, which is what Notes' `index.html` falls under.
Fixes #710.
> Disable 'Send to Notes' context menu item in Notes

- src/sidebar/static/css/styles-dark.css
> Use the correct background-color for both links and button in the dotted menu

- src/sidebar/app/components/Footer.js
Simply add On click a check in current state if footer is clickable or not.
Fix #708
> Disallow click event during syncing

- CHANGELOG.md
- package-lock.json
- package.json
- src/manifest.json
Things to test:
* Add send-to-notes context menu (#655)
* Add "Export as HTML" option (#695)
* Use React.js states to render the add-on frontend (#550)
cc @SoftVision-EmilPasca
> Preparing 3.0.0 release

- src/sidebar/app/components/Footer.js
- src/sidebar/app/utils/utils.js
Fixes https://github.com/mozilla/notes/issues/733
Fixes https://github.com/mozilla/notes/issues/735
Eventual fix for #735.
@vladikoff mind going over what I have so far? I feel as if I'm over-complicating things, but at the same time I feel like there's a lot needed to get the correct filename.
Per @ryanfeeley:
> OK, I spoke with the higher powers. We should follow was Firefox does when you Save Page As… and just use the title of the note.
> e.g Mattress Shopping.html no time stamp
> If the note is blank use: blank.html or better, disable the export note option in that state.
and 
> Yes, the first line that has text, it should use the text from that line to a maximum of 255 characters and just end it, no ellipsis.
My thought process was then:
1. **Notes not empty:** Notes has text in the …
> Use Notes content to name "Export as" filenames

- src/sidebar/static/scss/footer.scss
Ellipsis are not properly done in latest menu version. This PR fix it.
**Before**:
**After**:
> Fix text ellipsis too far from menu

- src/sidebar/static/css/styles-dark.css
Fixes #734. This adds the appropriate background colors when either hovering or when the button is focused or active. Also included was changing the syncing icon to be blue when hovered or in an active state, matching the default light theme.
> Fix styling for footer button (dark theme)

- src/sidebar/app/components/Footer.js
> Disable "Export" button while Notes syncs

- src/sidebar/app/utils/editor.js
> Prevent adding '„' character when Notes shortcut used within editor

- src/sidebar/app/components/Footer.js
Fixes #770 
Tested on Windows and works. Don't have a Linux machine so if someone else could verify that'd be great.
> Blur context menu button when menu closes

- src/background.js
- src/sidebar/app/onMessage.js
On send-to-note, we propagate windowId from background to react app which perform the action only if nto from an other window.
Have to be performed in sidebar react app since background do not know which note is displayed.
Fix #787
> Send to Note + Multi-Note + Multi-Window

- docs/metrics.md
- locales/en-US/notes.properties
- src/sidebar/app/actions.js
- src/sidebar/app/components/Footer.js
- src/sidebar/app/onMessage.js
- src/sidebar/app/reducers.js
- src/sidebar/app/utils/constants.js
- src/sync.js
After authenticating, kinto might return some errors we should handle.
Fix #791 #801 #802 #827
> Handle sync errors

- docs/metrics.md
- src/background.js
- src/sidebar/app/store.js
Add cd10 to every metrics request. Possible values are: **'error', 'isSyncing', 'synced', 'openLogin', 'verifyAccount', 'reconnectSync', and 'signIn'**.
Names are the one used by front-end to display proper footer UI.
We are not able for now to detect if a user synced on more than one device. This should be an improvement while working on the v5.mobile app.
Fix #771
> Add CD10 to all metrics

- src/sidebar/static/css/styles-dark.css
Fixes #834 and fixes #844.
- made title bar match the color of the '+ New Note' button
- icon buttons given proper :hover, :active, and :focus states
- made editor's editable area (background and color) match the rest of the dark theme
> Improvements to dark theme for multi-note support

- src/sync.js
- test/unit/main.test.js
Add a catch, but might be an issue regarding conflict solving.
Need to be tested and polished.
Fix #827
> Catch error 500 on delete

- src/sidebar/static/scss/menu.scss
Fixes #845
Sadly we cannot do a nice transition on Windows because then text is super shaky, sorry @sebastienbarbier  :(
> Fix CSS transition on Windows

- src/sidebar/app/utils/utils.js
The title of a note is wrongly displayed if the note contains only a list. This is now fixed 👍
Fix #861
> Fix formating on title if first item is a list

- src/sidebar/app/components/Editor.js
> Use ckeditor API to setFocus and solve some UI issue

- src/background.js
- src/sidebar/app/actions.js
- src/sidebar/app/components/Editor.js
- src/sidebar/app/components/EditorPanel.js
- src/sidebar/app/components/Header.js
- src/sidebar/app/components/ListPanel.js
- src/sidebar/app/onMessage.js
- src/sidebar/app/reducers.js
- src/sidebar/app/router.js
- src/sidebar/app/utils/constants.js
- src/sync.js
- test/unit/main.test.js
Having many issue syncing between multi-window notes, our data workflow was designed for single note. We were triggering `kinto-sync` on every event, performed asynchronously it was causing issues on create/delete/modify events.
Now we share events individually.
Fix #831 #858
> Refactor events workflow

- src/sync.js
This was caused by singleNote in v3 not having a lastModified date. 
After migration, when retrieving notes from kinto we were just ignoring this missing field and our UI was using new date() on load instead, causing this unwanted refresh.
This PR will check if every note has a lastModified value, and if not we will calculate it based on kinto last_modified record value.
Fix #868
> Fix wrong timestamp on delete

- src/sidebar/app/app.js
- src/sidebar/app/components/ListPanel.js
We now create initial note only if **first time using redux** AND **kinto is loaded** AND **it has no note**.
WIP, need more testing.
Fix #873
> Fix unexpected welcome note 

- src/sidebar/app/components/Editor.js
- src/sidebar/app/components/ListPanel.js
- src/sidebar/app/onMessage.js
Now works as expected.
Send-to-notes event has to be handle inside component instead of onMessage.js to be properly handled. Alternative is to share in redux state our navigation and have specific behaviour based on url but does not seams easier to maintain.
Fix #877
> Fix broken send-to-notes on empty note

- src/sidebar/static/css/styles-dark.css
Fixes #860. Ensures all photon menu items in the dark theme match the pseudo-classes of the default theme. Also fixed an issue with the `footer#footer-buttons.warning` element getting wrongly colored when focused (was becoming dark blue on focus, should stay the yellow warning color - this is fixed).
> Fix pseudo-classes for dark theme elements

- native/app/components/DrawerItems.js
You can guess that I am not super happy about how this PR has been implemented, but it works and catching drawer closing events does not seam like an easy option 😥.
Fix #968
> Delay redux disconnect event to avoid empty UI on logout

- native/app/utils/sync.js
Same as WebExtention, we receive NaN from Kintojs and can temporary solve this providing our own date.
Fix #984
> Fix issue for NaN last modified

- native/app/reducers.js
Looks like we forgot one use case when updating a note and generating firstLine/secondLine used in listPanel. This PR fixes it.
Fix #1000
> Add firstLine/secondLine generator on update action

- native/app/components/LoginPanel.js
On click, signin button now show a loading animation. 
Current action also redirect to `LoadingPanel` which hide the animation ... not sure if we want to keep this behaviour or if the animation still make sense.
Fix #948
> Add loading animation on signin button

- native/app/actions.js
- native/app/background.js
- native/app/components/EditorPanel.js
- native/app/components/ListPanel.js
- native/app/components/MoreMenu.js
- native/app/components/Snackbar.js
Fix #926, fix #1018, fix #1020
> Implement Snackbar notification for Notes Deleted 

- native/app/reducers.js
If a user is offine on logout, he should not be able to login. Assuming this, we now set `isConnected` as `true` on logout event 👍
Fix #1063
> Application no longer remains "offline" even after logging in.

- native/app/components/ListPanel.js
- native/app/components/Snackbar.js
Fixes https://github.com/mozilla/notes/issues/1083
> Improve undo button on delete snackbar

- native/app/components/ListPanelHeader.js
Was no longer openning. Tap was triggering openMenu(), now will trigger toggleMenu().
Fix #1077
> Fix double tap on the hamburger menu

- native/app/components/ListPanel.js
- native/index.js
I have two intermittent errors on master happening when starting the app:
> TypeError: Cannot read property 'colors' of undefined
> 
> This error is located at:
>     in StyledText (at withTheme.js:75)
>     in withTheme(StyledText) (at Title.js:29)
>     in Title (at DrawerItems.js:177)
Solved by adding `<PaperProvider>`  around our `<App>` component to load defaultTheme I guess _(we keep a second provider to keep the snackbar behind the drawer)_.
>  Invariant Violation: You must specify exactly one property per transform object. Passed properties: {"translateY":0,"scale":1}
Solved by fixing a syntax error which was not reported before.
> Fix paper theme loading and double transform error on FAB button

- src/sidebar/app/utils/editor.js
> Add keystroke for Ctrl/Cmd+S to ignore Save As popup

- src/sidebar/app/actions.js
- src/sidebar/app/onMessage.js
- src/sidebar/app/reducers.js
- src/sidebar/app/utils/constants.js
- src/sync.js
- test/unit/main.test.js
I had the same issue on the mobile app and could found a fix, but did not apply it to the browser add-on 😓. It's basically a conflict between the create request from the first letter and the update request for the followings.
Current solution consist to delay the create note and see if an update event follow to just ignore it.
Also, was really hard to reproduce on my machine, might be some condition making this more obvious in some case so might need special care while testing 😉.
Fix #1064
> Fix missing characters on sync between browser et mobile app

- native/app/actions.js
- native/app/background.js
- native/app/components/DrawerItems.js
- native/app/components/ListPanel.js
- native/app/components/LoadingPanel.js
- native/app/components/LoginPanel.js
- native/app/components/Snackbar.js
- native/app/reducers.js
- native/app/utils/sync.js
No longer open the drawer on reconnectSync error. 
Reconnect snackbar has unlimited duration, so will stay on screen until the user click on it to open the login page.
ALSO: reset kinto.js syncStatus on reconnectSync error to push local notes if user reset its password 🎉.
Fix #1066, Fix #1073
> ReconnectSync workflow using Snackbar

- .taskcluster.yml
- circle.yml
- native/android/app/build.gradle
- native/android/app/proguard-rules.pro
Reverts mozilla/notes#1117
Fixes https://github.com/mozilla/notes/issues/1118
Fixes https://github.com/mozilla/notes/issues/1119
> Revert "Target SDK 26 in Android"

- circle.yml
This should automate apk signing for everything pushed to the master branch. You can also require a tag by tweaking that tags.only regex.
I set the env var in circleci already, so it should just work :tm:
> Add logic to sign the APK from circleci

- native/android/app/src/main/java/com/notes/fxaclient/FxaClientModule.java
Second attempt at fixing #1320 
The previous commit's try catch only worked in the single threaded case -- this commit adds a "larger" catch that handles exceptions from all threads.
r? @vladikoff
> Catch coroutine exception in FxA login

- native/android/app/src/main/AndroidManifest.xml
Fixes #1336, #1337
From [Android docs](https://developer.android.com/guide/topics/manifest/activity-element#lmode), `singleTop` allows the activity to receive multiple intent from the base activity without necessarily creating multiple instances.
r? @vladikoff
> Prevent two sign-in windows from opening on Android

- src/sidebar/static/scss/styles.scss
For some reason the UA sheet loaded for extensions has a -moz-user-select: none
rule.
I have absolutely no clue why it's there, the commit message that introduced it
doesn't explain much.
In any case this is a very low-risk fix for the extension.
> Bug 1511391 - Fix the extension on Nightly and Beta.

- native/android/app/src/main/java/com/notes/FxaLoginActivity.java
- native/android/gradle.properties
- native/package-lock.json
The app can't be launched in dev mode without AndroidX.
To fix this we can enable these two options:
* `enableJetifier` => Jetifier is a tool to help project transition to AndroidX
* `useAndroidX` => Activates AndroidX
> Fix crash from AndroidX in development

- .babelrc
- package-lock.json
- package.json
This gets rid of the babel build step and uses Mocha's built in feature for compiling ES6 modules.
> Change mocha command for integration tests to use babel compiler.
