src/background.js
src/manifest.json
src/sidebar/options/options.html
src/sidebar/options/options.js
src/sidebar/panel.html
src/sidebar/panel.js

WIP PR so i can get @ryanfeeley setup

add fxa and update toolbar buttons

---

src/manifest.json
src/sidebar/panel.js

Add the encryption and decryption layers.

Add the encryption layer.

---

src/sidebar/panel.js

This PR adds basic conflict handling so that we don't loose data ever.
It also don't ask to merge conflicts that were supposed to be merged already.
Refs #14

Handle conflicts merge.

---

src/sidebar/panel.js

Add polling

---

.eslintignore
.eslintrc.yml
package.json
src/background.js
src/sidebar/options/options.js
src/sidebar/panel.js

The diff is a bit "extra noisy" because I ran `eslint src --fix` while I was at it.
Once this lands, I can reformat the code using **prettier** or something.

Fix up missing ESLint config and errors/warnings

---

.eslintrc.yml
package.json
src/background.js
src/sidebar/options/options.js
src/sidebar/panel.js
src/sidebar/styles.css

Add prettier for code beautification

---

README.md
circle.yml

Fixes https://github.com/mozilla/notes/issues/17

Add CircleCI

---

src/sidebar/panel.js

Set an allow list of pasted formats

---

src/sidebar/styles.css

Fix toolbar and footer styles

---

.eslintignore
.gitignore
package.json
scripts/postinstall.sh
src/background.js
src/manifest.json

Add metrics-library

---

.eslintrc.yml
package.json
scripts/postinstall.sh
src/sidebar/panel.html
src/sidebar/panel.js

Use JS-JOSE instead of custom crypto code.

---

scripts/postinstall.sh

Use minified versions of vendor libraries

---

.travis.yml

Not sure why some of my PRs aren't triggering Circle-CI, so let's see if we can do linting and builds on Travis-CI.

Run lint and build web extension on Travis-CI

---

README.md

Add a link to the pontoon dashboard.

---

src/sidebar/styles.css

Fixes https://github.com/mozilla/notes/issues/94

fix(styles): remove horizontal scroll

---

src/sidebar/panel.html
src/sidebar/panel.js

Fix font size menu.

---

src/manifest.json

Point add-on to correct updateURL

---

src/sidebar/panel.js

Fixes https://github.com/mozilla/notes/issues/108
Still work in progress, I want to add metrics to this
cc @Natim

disable drop events on the editor

---

.gitignore
bin/build-addon.sh

This isn't ready to land yet, but is close.  We still need to add permissions on AMO (I wasn't sure if this has been signed before or not) as well as address #122

first pass at a build-addon script; fixes #105

---

src/sidebar/panel.js

Remove header support for copy pasted content

---

src/sidebar/panel.js

Use DIV tags instead of P tags.

---

docs/metrics.md
package.json
scripts/postinstall.sh
src/background.js
src/manifest.json
src/sidebar/panel.js

Re: GA
> [10:03:11]  <@chuck>	vladikoff: just the GA measurement protocol, which is a simple POST to GA, with the data URL-encoded in the body. More info here: https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide
[10:03:24]  <@chuck>	+ here, which should be linked in the doc in your repo: https://github.com/mozilla/testpilot/blob/master/docs/experiments/ga.md

init work on latest metrics

---

src/sidebar/panel.html
src/sidebar/panel.js
src/sidebar/styles.css

Wait for a full loading before showing the editor. Fixes #137

Reduce startup states.

---

docs/metrics.md
src/background.js
src/sidebar/panel.js

Fixes #125
Please merge before merging #130

Add metrics to see how many users tries to drag something into the pad.

---

.eslintrc.yml
package.json
scripts/postinstall.sh
src/background.js
src/manifest.json

Use the testpilot-qa lib.

---

README.md

Also changes the style of the CircleCI badge to match.

Adds 'Available on Test Pilot' badge to README.

---

scripts/postinstall.sh
src/manifest.json

Rename testpilot-qa to testpilot-ga

---

src/manifest.json

Add Keyboard Shortcut

---

CHANGELOG.md

Fixes https://github.com/mozilla/notes/issues/166

Add Changelog md

---

package.json

Fixes Issue #200 on Windows(Git Bash)

---

src/sidebar/panel.js

Avoid race conditions in sidebar sync.

---

src/sidebar/panel.html

All changes saved should not act as a button.

---

src/sidebar/styles.css

Set default size to 14px.

---

CHANGELOG.md
src/sidebar/styles.css

Fix toolbar top border.

---

src/sidebar/panel.js

Disable right-click and spellchecker.

---

package.json
src/sync.js
test/unit/main.test.js

Fix #312 using the method introduced in Kinto/kinto.js#767.

Fix sync status

---

src/sidebar/panel.js

Disable sync your notes while editing status is displayed.

---

src/sidebar/panel.js

Display disconnect menu whenever connected.

---

src/sidebar/panel.js

Only prevent right clicks on the toolbar.

---

src/sidebar/panel.js

This is the second part that fixes #271. In the last PR, typing links
with active formatting was applied, but when pasting links any for-
matting would be dropped.
This PR fixes this issue by getting the active formats at the focus
of the editor then applies the formatting to the clipboard text
before pasting it to the editor. This applies to both text and links as
discussed in #322.

Give pasted text any active formatting

---

src/sidebar/styles.css

Make sure the font size is 14px.

---

src/sidebar/dark-svg/three-dots-dark.svg
src/sidebar/styles-dark.css

Add light-styled `three-dots.svg` for Dark Theme

---

src/sidebar/styles.css

Fix overlap between item number and content.

---

src/sync.js
test/unit/main.test.js

I forgot that you could recursively call syncKinto. Now that I saw
Rémy do it, let's do it in other places where it might be a good idea.

Add more retries

---

src/sidebar/panel.js
src/sidebar/styles.css

On click, trigger sendMessage('load-kinto') to sync with remote instance.
Also implement a boolean isAuthenticated to disable if user requested login but is not authenticated yet.
Related to #355

Implement manual sync

---

src/sidebar/panel.js

Handle new design at startup.

---

src/sidebar/panel.js

Use P rather than 14.

---

locales/en-US/notes.properties

Add editor migration note

---

ckeditor-build/src/markdown.js
package.json
src/sidebar/panel.js
src/sidebar/styles.css

@Natim this fixes a few bugs:
Fixes https://github.com/mozilla/notes/issues/421
Fixes https://github.com/mozilla/notes/issues/424
Fixes https://github.com/mozilla/notes/issues/420
Fixes https://github.com/mozilla/notes/issues/406
Fixes https://github.com/mozilla/notes/issues/407
Fixes https://github.com/mozilla/notes/issues/428
Related read for the reason to switch to HTML formatting: https://github.com/ckeditor/ckeditor5-markdown-gfm/issues/4

Fix data races and change storage format to HTML

---

package.json

Fixes: https://github.com/mozilla/notes/issues/429
PR: https://github.com/ckeditor/ckeditor5-autoformat/pull/43

Fix bad numbered list formatting

---

src/sidebar/panel.js

@Natim r?\
Fixes https://github.com/mozilla/notes/issues/437

Fix intro heading

---

src/sidebar/styles.css

Fixes https://github.com/mozilla/notes/issues/439

Align lists together

---

src/sidebar/editor.js
src/sidebar/panel.js

Fixes https://github.com/mozilla/notes/issues/491
Fixes https://github.com/mozilla/notes/issues/490

Handle drag and drop sync

---

.eslintrc.yml
src/background.js
src/sync.js

Re enabling sync with the same server should retrieve remote content.

---

.gitignore
src/sidebar/styles.css

As mentioned by @ryanfeeley and @vladikoff at #529, the unnecessary border has been fixed.
Please review

removed unneccesary border; Fixes #529

---

src/sidebar/editor.js

fixes: #518 .
I have fixed this. But the colour combinations may not be the best of all. So if you suggest me then surely I will change the colours accordingly.
The GIF below shows the changes made :)

side-bar now gets focused on dragging and dropping text

---

src/sidebar/styles-dark.css

As suggested by @Natim and marked out by @SoftVision-CarmenFat at #531, the inconsistencies have  been removed. Here's a preview of the same (its a long gif file, please be patient while it loads)
Please preview and suggest anymore changes to be made.

Inconsistencies in dark and default mode removed, Solves #531

---

src/sidebar/panel.html

fixes : #526 
Changes can be previewed below

The sync button no longer dislocates on being clicked

---

src/sidebar/menu.css
src/sidebar/panel.js
src/sidebar/styles.css

fixes : #487 
The text field will work as same as the Sync Button.

'Reconnect to Sync' text field acts as a button #487

---

src/sidebar/editor.js
src/sidebar/styles-dark.css
src/sidebar/styles.css

fixes : #562 
Below is a GIF of the changes made
~I have made a spelling mistake in my commit message. Shall I correct it ?~

The sidebar now gets focused on dragging and dropping text when dark theme is enabled

---

src/sidebar/styles.css

Fix for #569. How does the change look @ryanfeeley?
**Before:**
**After:**

Increase line height of list items

---

src/background.js

Fixes #554
Fixes #553 
cc @Natim

Remove setActiveIcon

---

src/sidebar/styles-dark.css

Fix "Give Feedback" item miscoloring in Dark theme

---

src/sidebar/styles.css

Set the min-width to match the minimum sidebar width.

---

src/manifest.json

Add in manifest browser_action theme_icons size 16

---

src/sidebar/styles.css

Use 100vh so that the footer doesn't bounce.

---

CHANGELOG.md
src/sidebar/panel.js

Fix single character edition not taken into account.

---

CHANGELOG.md
locales/en-US/notes.properties
package.json
src/sidebar/panel.js
src/sidebar/styles.css

Add the long form names in heading formatting.

---

src/sidebar/panel.js

Use kinto-load at startup to be much quicker.

---

src/sidebar/panel.js

Prevent dragging the give feedback button.

---

locales/en-US/notes.properties
src/sidebar/migration.js
src/sidebar/panel.js

Display a message when the notepad is growing too much.

---

src/sidebar/styles.css

fixes a part of #618 
Changed color according to this : https://design.firefox.com/photon/components/message-bars.html#warning
@Natim I am not sure about the second one. Couldn't find the properties respective to it. 
Having a hard time debugging the app. Can you recommend any tools for the same?

colour changed for max size warning 

---

package.json

Signed-off-by: Bhavya Aggarwal <bhavyaaggarwal1209@gmail.com>

Add script for running extension in Firefox Developer Edition

---

locales/nn-NO/notes.properties
src/sidebar/panel.js

Open feedback form in a new tab

---

src/sidebar/panel.js

fixes; #629 
GIF of the changes:

User email stored to local storage after enabling sync and removed after disabling sync

---

src/sidebar/panel.js

Give feedback menu item should not be dragable.

---

src/sidebar/styles-dark.css

related #568 
@Natim please review

Menu items fix for black theme

---

src/sidebar/panel.js

Replace all insecable spaces.

---

src/sidebar/styles.css

Hide context menu in savingMode.

---

docs/issue_template.md

fix #659 
reference : https://help.github.com/articles/creating-an-issue-template-for-your-repository/

issue template added

---

src/sidebar/panel.js

Do not truncate user content.

---

docs/metrics.md
src/background.js
src/sidebar/panel.js

Add new metrics event for limit reached

---

src/sidebar/panel.js

I think this is the only change which I could think of. Please see

"Sync with..." tooltip is wrongly displayed when hovering the "Give Feedback" button

---

src/sidebar/app/components/Footer.js
src/sidebar/app/constants.js

Add Notes version and Firefox versions in the survey URL

---

src/sidebar/app/components/Footer.js

Disable sync spin on save

---

src/sidebar/app/components/Footer.js

Moved tooltip in state object so we can easily customize it.
Also STATES is not part of FooterComponent to have direct access to state and read email or last modified date.

698 missing sync tooltip

---

src/background.js
src/sidebar/app/components/Footer.js

Add metrics to export to html

---

src/sidebar/app/components/Footer.js

Add a `Disable sync` tooltip in the menu.

---

src/sidebar/app/components/CloseIcon.js
src/sidebar/app/components/Editor.js
src/sidebar/static/scss/ckeditor.scss
src/sidebar/static/scss/styles.scss

Fixes https://github.com/mozilla/notes/issues/705

Fix broken max line limit in react version

---

src/sidebar/static/css/styles-dark.css

Fix Footer color issues for dark theme

---

.eslintrc.yml
README.md
docs/metrics.md
package-lock.json
package.json
scripts/postinstall.js
src/background.js
src/sidebar/static/css/styles-dark.css

@sebastienbarbier r?
Fixes #533

Remove quill refs

---

src/sidebar/app/components/Footer.js

Change feedback button from a to button and fix draggable issue

---

.eslintrc.yml
docs/metrics.md
src/background.js
src/manifest.json
src/utils.js

Related to https://github.com/mozilla/notes/issues/512
Fixes #722
@cedricium @pdehaan r? if u have time

Track IndexedDB errors

---

src/sidebar/static/scss/footer.scss

Fixes https://github.com/mozilla/notes/issues/526

Disable sync button movement

---

src/sidebar/app/components/Footer.js

Allow click on sync button during saving state.

---

src/sidebar/app/utils/utils.js

Make filenames truncate at 200 characters

---

src/sidebar/app/components/ListPanel.js

Fixes https://github.com/mozilla/notes/issues/792

Remove titles from ListPanel Items

---

src/sidebar/static/scss/ckeditor.scss

Fix styles for the toolbar, hide overflow

---

src/sidebar/app/components/ListPanel.js
src/sidebar/app/utils/editor.js

Disable context menu in the list view

---

src/icons/notes-fill.svg
src/manifest.json

Make browserAction match theme

---

src/sidebar/app/reducers.js

Remove empty line when using send-to-notes

---

src/sidebar/static/scss/ckeditor.scss

Fix toolbar dropdown and resize overlay

---

src/sidebar/static/css/styles-dark.css

Fixes #785.
@vladikoff / @ryanfeeley, I'm not sure how we want to style the header (where the title, back and context menu buttons are located - see below)? I'd almost like to just leave it as is… thoughts?

Fix dark theme for Multi-Notes

---

src/sidebar/static/scss/list.scss

Dropped font weight from 600 to 500 to make it semibold

Dropped font weight from 600 to 500

---

src/sidebar/app/components/Editor.js

Fix copy paste in ckeditor (#830)

---

package-lock.json
package.json
src/manifest.json
src/sidebar/app/actions.js

Using : https://github.com/eligrey/FileSaver.js
Fix #789

Refactor export-to-html now using SaveFile lib instead of download API

---

src/sidebar/static/scss/footer.scss
src/sidebar/static/scss/header.scss

Change buttons color from header and footer now using Photon value

---

src/background.js
src/sidebar/app/actions.js
src/sidebar/app/app.js
src/sidebar/app/components/ListPanel.js
src/sidebar/app/onMessage.js
src/sidebar/app/reducers.js

Fixes https://github.com/mozilla/notes/issues/832

Fix send to notes for react router

---

src/sidebar/app/components/Editor.js

Focus editor on new note

---

src/background.js
src/sidebar/app/app.js
src/sync.js

PR fix this issue, but we lose authentication after migration since email was not stored locally in v3. Hope that is ok.
Fix #879

Fix crash on migration while synced

---

src/background.js

Fixes https://github.com/mozilla/notes/issues/901
@sebastienbarbier please confirm, r?

Fix the wacky refresh on toolbar press

---

locales/en-US/notes.properties

A few mismatches from the mockup that I decided to fix or break things on GitHub

Copy tweaks mostly title case

---

native/android/app/src/main/AndroidManifest.xml
native/app/utils/constants.js

Fixes https://github.com/mozilla/notes/issues/900

Make mobile talk to prod servers

---

native/app/utils/constants.js
native/index.js

Update status bar colours

---

native/app/utils/sync.js

@vladikoff : You gonna like that one 😉 
Fix #961

Fix encoding on mobile

---

native/app/actions.js
native/app/background.js
native/app/components/DrawerItems.js
native/app/components/ListPanel.js
native/app/components/LoginPanel.js
native/app/components/SplashPanel.js
native/app/reducers.js

Pull to refresh now update the "Last Synced" date

---

native/app/actions.js
native/app/background.js
native/app/components/EditorPanel.js
native/app/components/ListItem.js
native/app/components/ListPanel.js
native/app/components/MoreMenu.js

Fix #982 Fix #993 Fix #989 Fix #996 Fix #1003

Editor now use note.id to retrieve content from redux state

---

native/app/components/ListPanel.js

"No notes" view still need to be implemented (#945)
Fix #995

Swipe down to sync now work while having no notes

---

native/app/components/ListItem.js
native/app/reducers.js
native/app/utils/utils.js

Hide nbsp from viewPanel

---

native/app/actions.js
native/app/background.js
native/app/components/EditorPanel.js
native/app/components/ListItem.js
native/app/components/ListPanel.js
native/app/components/MoreMenu.js
native/app/reducers.js
native/app/utils/sync.js

Try to make syncing less agressive. Simple first version with longer delay and optimised creation ... works well, worth testing.
Fix #998

Clean up requests and syncing logic

---

native/app/components/EditorPanel.js
native/app/components/ListItem.js

Use proper ellipsis in contentPlaceholder='Take a note...'

---

native/app/utils/sync.js

Fix empty list of notes when logging in after signing out

---

native/app/components/ListPanel.js
native/app/components/ListPanelEmpty.js
native/app/components/ListPanelLoading.js

Implement the no notes view

---

native/app/components/DrawerItems.js
native/app/components/ListPanelHeader.js
native/app/components/LoadingPanel.js
native/app/components/LoginPanel.js
native/app/components/MoreMenu.js
native/app/components/SplashPanel.js
native/index.js
native/package-lock.json
native/package.json

Using react-navigation 2.0 **simplify our workflow** _(which now triggers componentWillUnmount() if using StackNavigator using navigate('...'))_. Also fix #997.

Upgrade react-navigation from v1.5.x to 2.0.0

---

docs/metrics.md
native/app/actions.js
native/app/background.js
native/app/components/DrawerItems.js
native/app/components/EditorPanel.js
native/app/components/ListPanel.js
native/app/components/MoreMenu.js
native/app/utils/metrics.js
native/app/utils/sync.js
native/index.js

@vladikoff can you check if metrics are properly received on GA ? 👍
Fix #911

Implement all GA events 

---

native/app/components/EditorPanelHeader.js
native/app/components/MoreMenu.js

Fix hitbox on back button and center title

---

native/app/components/DrawerItems.js
native/app/components/EditorPanelHeader.js
native/app/components/ListPanel.js
native/app/utils/sync.js
native/index.js
native/package-lock.json
native/package.json

Handle full storage errors

---

native/app/components/ListPanel.js

Improve FAB design by fixing shadow issue (fix #1061) and animate when switching on selection mode.

Improve FAB button in listPanel

---

native/app/components/DrawerItems.js

Sync button is pressed multiple times but now triggered once

---

native/app/components/MoreMenu.js

Is popupmenu is open, we do nothing
Fix #1049

Multiple tap on note menu now open the popupmenu only once 

---

native/app/components/ListItem.js

Larger notes selector in PanelView

---

native/app/components/DrawerItems.js

Tapping "Notes Storage Full" no longer display "Log In" page

---

native/app/actions.js
native/app/components/ListPanel.js
native/app/components/MoreMenu.js
native/app/components/Snackbar.js
native/index.js
native/package-lock.json
native/package.json

Stabilise Snackbar and drawer features

---

native/app/components/SplashPanel.js

No more`Reconnect to Sync` if the app start offline.

---

native/app/components/DrawerItems.js
native/index.js

Disable drawer on EditorPanel

---

native/app/components/LoadingPanel.js
native/index.js

Fixes https://github.com/mozilla/notes/issues/1058

Fix white screen on sign in dismiss

---

native/app/components/ListPanel.js

Fix snackbar height

---

native/android/app/src/main/assets/editor.html
native/app/react-native-zss-rich-text-editor/src/editor.html

Remove blank space that is left after keyboard is closed

---

src/sidebar/app/onMessage.js

Stop "Syncing Changes..." on new notes

---

native/android/build.gradle
native/app/components/DrawerItems.js

Fix drawer reconnect crash

---

native/android/app/src/main/assets/editor.html
native/app/utils/utils.js

Update firstLine and secondLine functions.

---

src/sidebar/app/components/Editor.js

Do not create empty note.

---

src/sidebar/app/actions.js
src/sidebar/app/components/ListPanel.js

Use a given ID to make sure we never create multiple welcome notes.

---

src/fxa-utils.js
src/sidebar/app/components/Editor.js
src/sidebar/app/components/EditorPanel.js
src/sidebar/app/components/Footer.js
src/sidebar/app/components/ListPanel.js
src/sidebar/app/utils/utils.js
src/sync.js

Since some updates happend, here are the changes mandatory to fix that.

---

src/fxa-utils.js
src/sidebar/app/components/Editor.js
src/sidebar/app/components/EditorPanel.js
src/sidebar/app/components/Footer.js
src/sidebar/app/components/ListPanel.js
src/sidebar/app/utils/utils.js
src/sync.js

Revert "Since some updates happend, here are the changes mandatory to fix that."

---

src/sidebar/static/scss/ckeditor.scss

Fixes #1172
Fixes #1169
Fixes #1168
Fixes #1167
Fixes #1166
Fixes #1165
Fixes #1164

Fix CKEditor stable issues

---

src/sidebar/static/css/styles-dark.css

Fix dark theme editor background

---

src/sidebar/app/actions.js
src/sidebar/app/components/Header.js
src/sidebar/static/scss/header.scss

Fixes to export as html logic

---

src/sidebar/app/components/ListPanel.js
src/sidebar/static/scss/ckeditor.scss
src/sidebar/static/scss/footer.scss
src/sidebar/static/scss/list.scss
src/sidebar/static/scss/styles.scss

Fix focus style in heading dropdown, Lighter border for list view items

---

src/sidebar/app/components/Editor.js

Fix Add to Notes option is not saved

---

src/sync.js
test/unit/index.js

Fixes https://github.com/mozilla/notes/issues/983

Replace cryptographer with node-jose in the webextension

---

native/app/components/EditorPanel.js
native/app/components/ListPanel.js
native/app/reducers.js
native/package-lock.json
native/package.json

Fix sorting alg for dates and optimize views

---

locales/en-US/notes.properties
native/app/actions.js
native/app/components/DrawerItems.js
native/app/components/EditorPanelHeader.js
native/app/components/ListPanel.js
native/app/components/ListPanelEmpty.js
native/app/components/ListPanelHeader.js
native/app/components/LoadingPanel.js
native/app/components/LoginPanel.js
native/app/components/MoreMenu.js
native/app/utils/i18n.js

Fixes https://github.com/mozilla/notes/issues/1176
Fixes https://github.com/mozilla/notes/issues/957
@flodolo r?

Add mobile strings

---

native/app/components/ListPanel.js

Fix loading from sign in / sign up on mobile

---

src/sidebar/static/scss/ckeditor.scss

Fix padding between buttons in the toolbar

---

native/app/components/EditorPanelHeader.js
native/index.js

Clean up status bar colors

---

native/app/components/ListPanel.js
native/app/components/ListPanelWrapper.js
native/app/components/LoadingPanel.js
native/app/components/LoginPanel.js
native/index.js

Update background colors

---

native/app/components/EditorPanel.js
native/app/components/LoginPanel.js
native/app/components/MoreMenu.js
native/app/utils/constants.js
native/app/vendor/fxa-utils.js

Style fixes and update to use the new FxA Auth url

---

native/android/app/src/main/assets/editor.html
native/app/components/EditorPanel.js
native/app/react-native-zss-rich-text-editor/src/editor.html

Fixes #1245 
Fixes #1248
Fixes #1243

Fix Heading Sync, add loading indicator

---

native/app/utils/utils.js

Fix formatting for secondary line

---

native/app/actions.js
native/app/components/DrawerItems.js
native/app/components/ListPanel.js
native/app/components/ListPanelWrapper.js
native/app/components/MoreMenu.js

Fix 'syncing...' looping on undo

---

native/app/components/LoginPanel.js

Fixes https://github.com/mozilla/notes/issues/1264

Fix title padding for oneplus

---

native/app/utils/i18n.js

Fix regression with translations

---

native/android/app/src/main/AndroidManifest.xml
native/android/app/src/main/java/com/notes/fxaclient/FxaClientModule.java

r? @vladikoff 
Fixes #1320 
Fixes #1322

Fix Softvision QA issues

---

native/android/app/src/main/java/com/notes/fxaclient/FxaClientModule.java

Fix #1320: Catch coroutine exception on FxA login

Catch coroutine exception in FxA login

---

package-lock.json
test/integration/page_objects/note_page.js
test/integration/testFirefoxWebext.js

1. ```should be able to delete a note```: tests that a user is able to delete a note.
2. ```should be able to add a note from the note page```: tests that you can create a new note from the note page.
3. ```should be navigate to feedback page```: tests that the 'Give Feedback' button routes to the correct page.

Added 3 new integration tests.

---

package-lock.json
src/sidebar/app/components/ListPanel.js
src/sidebar/static/scss/list.scss

Hi,
Fix for https://github.com/mozilla/notes/issues/1209 has been added by making following changes:
**Problem Description:**
The List View cannot be scrolled using the keyboard
**Solution:**
1. 
'keydown' event for 'ArrowUp' and 'ArrowDown' keys has been handled by adding an event handler 'handleKeyPress' in src/sidebar/app/components/ListPanel.js.
2. 
Pseudo class "focus" has been added in src/sidebar/static/scss/list.scss to add background color to currently selected note.
Please review the changes and let me know your comments/suggestions.
Thanks!

Fixes https://github.com/mozilla/notes/issues/1209

---

native/android/app/build.gradle

Fixes https://github.com/mozilla/notes/issues/1345

Use latest android components, fix build.gradle

---

CHANGELOG.md
package.json
src/manifest.json

Fixes https://github.com/mozilla/notes/issues/1435

Release v4.2.1

---

CHANGELOG.md
package.json
src/manifest.json

Release 4.3.0

---

CHANGELOG.md
package.json
src/manifest.json

Release v4.3.2

---

CHANGELOG.md
package.json
src/manifest.json

Release 4.3.6
